all:
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no -o IdentitiesOnly=yes
    ansible_become: true
    ansible_user: vagrant
    security_mode: plaintext
preflight:
  hosts:
    broker1:
      ansible_host: 127.0.0.1
      ansible_port: 2231
    broker2:
      ansible_host: 127.0.0.1
      ansible_port: 2232
    broker3:
      ansible_host: 127.0.0.1
      ansible_port: 2233
zookeeper:
  hosts:
    broker1:
    broker2:
    broker3:
broker:
  hosts:
    broker1:
      kafka:
        broker:
          id: 1
    broker2:
      kafka:
        broker:
          id: 2
    broker3:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    broker1:
control-center:
  hosts:
    broker2:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: broker1:8083
connect-distributed:
  hosts:
    broker1:
kafka-rest:
  hosts:
    broker1:
ksql:
  hosts:
    broker1:
