all:
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no -o IdentitiesOnly=yes
    ansible_become: true
    ansible_user: vagrant
    security_mode: kerberos
    realm: domenic.example.com
    kdc_hostname: node4
    admin_hostname: node4
    keytab_source_dir: /Users/dbove/workspace/vagrant-confluent/keytabs/
preflight:
  hosts:
    node1:
      ansible_ssh_host: 127.0.0.1
      ansible_ssh_port: 2231
    node2:
      ansible_ssh_host: 127.0.0.1
      ansible_ssh_port: 2232
    node3:
      ansible_ssh_host: 127.0.0.1
      ansible_ssh_port: 2233
ssl_CA:
  hosts:
    node1:
kerberos:
  hosts:
    node1:
    node2:
    node3:
zookeeper:
  hosts:
    node1:
    node2:
    node3:
broker:
  hosts:
    node1:
      kafka:
        broker:
          id: 1
    node2:
      kafka:
        broker:
          id: 2
    node3:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    node1:
control-center:
  hosts:
    node2:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: node1:8083
connect-distributed:
  hosts:
    node1:
kafka-rest:
  hosts:
    node1:
ksql:
  hosts:
    node3:
kerberos-server:
  hosts:
    node4:
      ansible_ssh_host: 127.0.0.1
      ansible_ssh_port: 2234
      realm_name: "{{ realm | upper }}"
