---
- hosts: kerberos_server
  roles:
   - kerberos_server

- hosts: kerberos_server
  tasks:
  - name: keytabs dir
    file:
      path: /tmp/keytabs/
      state: directory
      mode: 0755

- hosts: zookeeper:kafka_broker:schema_registry:kafka_connect:ksql:control_center:kafka_rest
  tasks:

   - name: addprinc
     shell: "kadmin.local -q 'addprinc -randkey {{ item }}/{{ inventory_hostname }}@{{ kerberos.realm | upper }}'"
     delegate_to: "{{ groups['kerberos_server'][0] }}"
     with_items:
       - kafka
       - zookeeper
       - cp-zk
       - schemaregistry
       - restproxy
       - cp-connect
       - controlcenter
       - client

   - name: Create kafka keytab
     shell: "kadmin.local -q 'xst -norandkey -k /tmp/keytabs/{{ inventory_hostname }}.keytab kafka/{{ inventory_hostname }}@{{ kerberos.realm | upper }}'"
     delegate_to: "{{ groups['kerberos_server'][0] }}"

   - name: Create rest of the keytabs
     shell: "kadmin.local -q 'xst -norandkey -k /tmp/keytabs/{{ item }}-{{ inventory_hostname }}.keytab {{ item }}/{{ inventory_hostname }}@{{ kerberos.realm | upper }}'"
     delegate_to: "{{ groups['kerberos_server'][0] }}"
     with_items:
       - zookeeper
       - cp-zk
       - schemaregistry
       - restproxy
       - cp-connect
       - controlcenter
       - client

- hosts: kerberos_server
  tasks:
  - name: copy keytabs back
    synchronize:
      src: /tmp/keytabs/
      dest: keytabs
      mode: pull
